import Head from 'next/head';
import styles from '../styles/Home.module.css';
import type { GetServerSideProps } from 'next';
import { unstable_getServerSession } from 'next-auth';
import { options } from './api/auth/[...nextauth]';
import type { MemoType } from '../types/MemoType';
import { signIn, useSession } from 'next-auth/react';
import Layout from '../components/Layout';
import { ParsedUrlQuery } from 'querystring';
import Memo from '../components/Memo';
import { prisma } from '../lib/prisma';

export const getServerSideProps: GetServerSideProps = async ({
  params,
  req,
  res,
}) => {
  const session = await unstable_getServerSession(req, res, options);
  if (!session) {
    return {
      props: {
        memos: null,
      },
    };
  }

  const memos = await prisma.memo.findMany({
    where: {
      authorId: session.user_id,
    },
    orderBy: {
      updatedAt: 'desc',
    },
  });

  return {
    props: {
      memos,
      params,
    },
  };
};

type Props = {
  memos: MemoType[];
  params: ParsedUrlQuery;
};

const Home = (props: Props) => {
  const { data: session, status } = useSession();

  if (status === 'loading') {
    <div>Loading...</div>;
  }

  if (!session) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Memo App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to Memo App!</h1>

          <button className="btn btn-primary" onClick={() => signIn()}>
            Login
          </button>
        </main>
      </div>
    );
  }

  if (session && props.memos !== null) {
    return (
      <Layout>
        <div className="grid grid-flow-row gap-4 md:grid-cols-1 lg:grid-cols-3">
          {props &&
            props.memos.map((memo) => <Memo key={memo.id} memo={memo} />)}
        </div>
      </Layout>
    );
  }
};

export default Home;
